add majica customer rule

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -1,6 +1,24 @@
 #!/bin/bash
 
 # =======================================================
+# Majica customer rule
+# =======================================================
+BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
+
+PATTERN="^(feature|release|hotfix)/[a-zA-Z0-9_]+_[0-9]{8}/[a-zA-Z0-9_]+/[0-9]+"
+
+if [[ !$BRANCH_NAME=~$PATTERN ]];then
+  echo "Error: Branch name does not match the naming convention."
+  echo "Required format: <Branch Type>/<Task Type>_<Release Date>/<Team ID>/<PPIH Redmine Ticket ID>/<Description>"
+  echo "Example: feature/mk_20260430/ai/12345678/add-login-form"
+  echo "Current: $BRANCH_NAME"
+  exit 1
+fi
+# =======================================================
+# =======================================================
+
+
+# =======================================================
 # == CẤU HÌNH WHITELIST (Chỉ cho phép mẫu này)
 # =======================================================
 # Mẫu regex BẮT BUỘC
